### ISSUE TITLE
Tenosrflow Documentation: Load and preprocess images 

### ISSUE THREAD

**Issue by FLX-20** [FLX-20/Data-Science-Toolkits-and-Architectures-group-1#18]
Why does the copied code from the [tensorflow documentation](https://www.tensorflow.org/tutorials/load_data/images) result in 0?
According to the documentation, the number of images in the directory should be returned.

```python
import pathlib
import tensorflow as tf
dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
archive = tf.keras.utils.get_file(origin=dataset_url, extract=True)
data_dir = pathlib.Path(archive).with_suffix('')

image_count = len(list(data_dir.glob('*/*.jpg')))
print(image_count)
```

**Comment by Tjerk8389** [comment]
There is probably something from with this code:

data_dir = pathlib.Path(archive).with_suffix('')

You need to correctly set data_dir to the folder where it is extracted, which contains the image files.
