### ISSUE TITLE
Task 1 milestone 3: Install docker-compose

### ISSUE THREAD

**Issue by FLX-20** [FLX-20/Data-Science-Toolkits-and-Architectures-group-1#39]
Install docker-compose. And got through this:
https://docs.docker.com/compose/gettingstarted/

**Comment by FLX-20** [comment]
Have you successfully installed docker compose? Can you ran a build a yaml file and run it with docker-compose?

**Comment by FLX-20** [comment]
@Tjerk8389 please share your solutions of Task 1 one on GitHub.

**Comment by Tjerk8389** [comment]
Yes I have succesfully installed Docker compose, if i use this command in my terminal ''docker compose version'' I get this output ''Docker Compose version v2.29.2-desktop.2''.

**Comment by FLX-20** [comment]
Please go the main-dev-branch of  milestone 3 now and try to `docker-compose up` in the root directory.
If you confirgured everything well and if I programmed everything correct the model should be trained and tested automatically.
Running everthing might take some time even if there are no errors.

**Comment by Tjerk8389** [comment]
I cannot find the main-dev-branch of milestone 3, if I want to switch to main-dev-3-branch I get this error message ''fatal: invalid reference: main-dev-3-branch''. I already used Git pull after the git clone. 

Also I don't see the branch on github, the active branches are: main-report-3-branch, sql-image-database, report3-chapter3, main-dev-4-branch, main-report-4-branch.

That is why I created the branch called report3_chapter1, and that is where I post all the information about the first exercise of the docker compose

**Comment by Tjerk8389** [comment]
I have completed it

**Comment by FLX-20** [comment]
You can not completed it, because I created a pull request for the wrong branch. I merged the `sql-image-database` branch into the `main-report-3-branch`accidentally. I corrected it now and merged it into the `main-dev-3-branch`. Please try out again, if you can run the entire code just be `docker-compose up` without errors.

**Comment by Tjerk8389** [comment]
Do you want me to add the folder and files from the tutorial of docker compose to our Github repository? The files in the `composetest` and the files in that folder are: `app.py` `compose.yaml` `Dockerfile` `infra.yaml` `requirements.txt`.

**Comment by FLX-20** [comment]
No the tutorial You do for yourself. This is not part of our core project.
