### ISSUE TITLE
Task 1 milestone 3: Documentation

### ISSUE THREAD

**Issue by FLX-20** [FLX-20/Data-Science-Toolkits-and-Architectures-group-1#40]
Answer the following questions in the documentation of the report
- Which services are being used for the application (described in the link above)? How do they relate
to the host names in terms of computer networks?
- What ports are being used (within the application and in the docker-compose file)?
- How does the host machine (e.g. your computer) communicate with the application inside the
Docker container. Which ports are exposed from the application to the host machine?
- What is localhost, why is it useful in the domain of web applications?

**Comment by Tjerk8389** [comment]
Do you also want me to list all the steps that were done in the tutorial?

**Comment by FLX-20** [comment]
Describe the process in a way that one can follow the steps and come to the same results, like you without any room for uncertainty.
But this task is actually assigned to @igilan80 . Please communicate with each other who will do this task and then reassign it if required.

**Comment by Tjerk8389** [comment]
I know that this task is assigned to @igilan80 but we all needed to do the first step of task 1, the docker compose tutorial. So I only completed that, the rest is of the exercise he will make.

**Comment by FLX-20** [comment]
Ok perfect. Thanks for your clarification.

**Comment by Tjerk8389** [comment]
@igilan80 can add the rest of task 1
