### ISSUE TITLE
Task 1 milestone 4: Answer general questions

### ISSUE THREAD

**Issue by FLX-20** [FLX-20/Data-Science-Toolkits-and-Architectures-group-1#44]
Answer the following questions:
- What is Experiment Management and why is it important?
- What is a Metric in ML?
- What is Precision and Recall? Why is there often a trade-off between them?
- What is AUROC Metric?
- What is a Confusion Matrix?

**Comment by Tjerk8389** [comment]
@igilan80 needs to see if he wants to make changes to this task, because we both made the task so we can have an answer which is based on two perspectives
