### ISSUE TITLE
Task 3 milestone 4: analyze your data in Jupyter Notebook

### ISSUE THREAD

**Issue by FLX-20** [FLX-20/Data-Science-Toolkits-and-Architectures-group-1#46]
- Load your data into a Numpy Array (f.e. If you have Image data, load an image and you should get an array
with dimensions (width, height, channels), where channels is 3 in an RGB image (Red,Green and Blue
colors).
- Use Numpy to analyze your data. F.e. you could create a histogram of the color channels, or the distribution
of words in your training set (in case you have text data). Use Matplotlib to plot figures.
- Analyze the output of your Training runs from Task 2. This means:
download the ground truth of your data set and the predictions your Neural Network made. You may try to
create a Confusion Matrix with Scikit-Learn.

**Comment by Tjerk8389** [comment]
You have appointed this task to us both @FLX-20, how do you want to divide this task explicitly between us?

**Comment by Tjerk8389** [comment]
Last dot ''Analyze the output of your Training runs from Task 2. This means: download the ground truth of your data set and the predictions your Neural Network made. You may try to create a Confusion Matrix with Scikit-Learn.'' is already done

**Comment by FLX-20** [comment]
I already implemented the confusion matrix in the second milestone.
My suggestions for the dataset analysis would be:
- write the Python code to download the image from the URL
- find out basic information about the dataset (number of images, number of classes, number of images per class, height and width of the images and so on ...)
- save the images of the three classes (dogs, cats and snakes) in three different numpy arrays
- display a 3x3 grid of 9 random images from each class
- analyze and compare these arrays
- Create the RGB histograms for each class (one histogram for each colour channel, represented next to each other)
- Compare the histograms of the classes
- Convert the images into HSL (Hue, Saturation, Lightness) 
- Create the histograms again in the same way and compare the class based on these histograms
- Connect your results and findings with the convolution matrix of the models
- extra task: reduce image dimensions (e.g., using PCA) to visualize the dataset in a 2D space and identify clusters or overlaps between classes.

**Comment by FLX-20** [comment]
I finished the image data analysis of our dataset. I did not included the PCA, because it did not produced meaningful results for the 2D scenario.
