### ISSUE TITLE
Finished chapter go to the main-report-branch.

### ISSUE THREAD

**Issue by FLX-20** [FLX-20/Data-Science-Toolkits-and-Architectures-group-1#51]
Don't push single finished chapters into the main branch. This is the production branch on which we push final results in the end of the sprint/milestone.

Please undo the merge of `report3-chapter1` into `main` branch, before you do anything else.
Afterwards merge `report3-chapter1`  into m̀ain-report-3-branch`.

**Comment by FLX-20** [comment]
I reverted the merge and increased the number of reviews to 2, so that you can not merge again something accidentally to the main branch.

**Comment by Tjerk8389** [comment]
I have completed this step. Now @igilan80 can add his changes into the report3-chapter1 branch to finish Task1.
